#db:
#  mysql.url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#  mysql.username: root
#  mysql.password: 12345678
#  mysql.driver: com.mysql.jdbc.Driver

spring:
  datasource:
    ds1:
      type: com.mchange.v2.c3p0.ComboPooledDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.2.131:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: 12345678
      initialSize: 3
      maxActive: 100
      minIdle: 10
      maxWait: 5000

    ds2:
      type: com.mchange.v2.c3p0.ComboPooledDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.92.35.78:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: YUKUCONNECT
      password: 012345
      initialSize: 3
      maxActive: 100
      minIdle: 10
      maxWait: 5000


