
package  com.promotion.product.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IKmReviewWebserviceService", targetNamespace = "http://webservice.review.km.kmss.landray.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IKmReviewWebserviceService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addReview", targetNamespace = "http://webservice.review.km.kmss.landray.com/", className = "com.landray.kmss.km.review.webservice.AddReview")
    @ResponseWrapper(localName = "addReviewResponse", targetNamespace = "http://webservice.review.km.kmss.landray.com/", className = "com.landray.kmss.km.review.webservice.AddReviewResponse")
    public String addReview(
        @WebParam(name = "arg0", targetNamespace = "")
                KmReviewParamterForm arg0)
        throws Exception_Exception
    ;

}
